/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2018-05-18 17:52:15 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/stream -t views -t users -t blacklist -t txs -t upvotes -t refresh_tokens -t access_tokens -t platforms -t promoblacklist -s public
 *
 */

export namespace viewsFields {
    export type id = string;
    export type user_id = string | null;
    export type video_url = string;
    export type video_id = string;
    export type platform_id = string;
    export type platform_type = string;
    export type datetime = Date;

}

export interface views {
    id: viewsFields.id;
    user_id: viewsFields.user_id;
    video_url: viewsFields.video_url;
    video_id: viewsFields.video_id;
    platform_id: viewsFields.platform_id;
    platform_type: viewsFields.platform_type;
    datetime: viewsFields.datetime;

}

export namespace usersFields {
    export type id = string;
    export type username = string;
    export type email = string;
    export type password = string;
    export type phone = string | null;
    export type address = string | null;
    export type prof_pic = string | null;
    export type referral_code = string;
    export type referrer_id = string | null;
    export type permalink = string | null;
    export type verify_token = string | null;
    export type verified = boolean;

}

export interface users {
    id: usersFields.id;
    username: usersFields.username;
    email: usersFields.email;
    password: usersFields.password;
    phone: usersFields.phone;
    address: usersFields.address;
    prof_pic: usersFields.prof_pic;
    referral_code: usersFields.referral_code;
    referrer_id: usersFields.referrer_id;
    permalink: usersFields.permalink;
    verify_token: usersFields.verify_token;
    verified: usersFields.verified;

}

export namespace blacklistFields {
    export type token = string;

}

export interface blacklist {
    token: blacklistFields.token;

}

export namespace txsFields {
    export type tx_hash = string;
    export type tx_status = string;
    export type tx_type = string;
    export type value = string;
    export type sender_user_id = string | null;
    export type sender_address = string | null;
    export type recipient_user_id = string | null;
    export type recipient_address = string | null;
    export type recipient_platform_type = string | null;
    export type recipient_platform_id = string | null;
    export type message = string | null;
    export type metadata = string | null;
    export type datetime = Date | null;

}

export interface txs {
    tx_hash: txsFields.tx_hash;
    tx_status: txsFields.tx_status;
    tx_type: txsFields.tx_type;
    value: txsFields.value;
    sender_user_id: txsFields.sender_user_id;
    sender_address: txsFields.sender_address;
    recipient_user_id: txsFields.recipient_user_id;
    recipient_address: txsFields.recipient_address;
    recipient_platform_type: txsFields.recipient_platform_type;
    recipient_platform_id: txsFields.recipient_platform_id;
    message: txsFields.message;
    metadata: txsFields.metadata;
    datetime: txsFields.datetime;

}

export namespace upvotesFields {
    export type id = string;
    export type user_id = string | null;
    export type video_id = string;
    export type platform_id = string;
    export type platform_type = string;
    export type upvoted = boolean;
    export type datetime = Date;

}

export interface upvotes {
    id: upvotesFields.id;
    user_id: upvotesFields.user_id;
    video_id: upvotesFields.video_id;
    platform_id: upvotesFields.platform_id;
    platform_type: upvotesFields.platform_type;
    upvoted: upvotesFields.upvoted;
    datetime: upvotesFields.datetime;

}

export namespace refresh_tokensFields {
    export type id = string;
    export type token = string | null;
    export type user_id = string | null;
    export type client_id = string | null;

}

export interface refresh_tokens {
    id: refresh_tokensFields.id;
    token: refresh_tokensFields.token;
    user_id: refresh_tokensFields.user_id;
    client_id: refresh_tokensFields.client_id;

}

export namespace access_tokensFields {
    export type id = string;
    export type token = string | null;
    export type user_id = string | null;
    export type client_id = string | null;
    export type expires = number | null;

}

export interface access_tokens {
    id: access_tokensFields.id;
    token: access_tokensFields.token;
    user_id: access_tokensFields.user_id;
    client_id: access_tokensFields.client_id;
    expires: access_tokensFields.expires;

}

export namespace platformsFields {
    export type id = string;
    export type user_id = string;
    export type platform_id = string;
    export type platform_type = string;

}

export interface platforms {
    id: platformsFields.id;
    user_id: platformsFields.user_id;
    platform_id: platformsFields.platform_id;
    platform_type: platformsFields.platform_type;

}

export namespace promoblacklistFields {
    export type user_id = string;

}

export interface promoblacklist {
    user_id: promoblacklistFields.user_id;

}
